language: go

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

go:
 - 1.10
 - 1.11
 - 1.12

install:
 - go get -u github.com/golang/dep/cmd/dep
 - go get -u github.com/golang/go/src/cmd/gofmt
 - go get golang.org/x/crypto/ssh/terminal

script:
 - go vet .
 - go fmt .
 - gofmt -e -s -w .
 - dep ensure -update -v
 - travis_wait 20 go test -p 10 -timeout 20m -v -cover -covermode atomic ./test/...
 - go build -buildmode exe -pkgdir ./vendor .
